### ISSUE TITLE
フロントエンドのパラメータストアにフロントエンドのURLを追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-terraform#109]
# Doneの定義
- 表題の通り

# 補足
https://github.com/nekochans/qiita-stocker-nuxt/pull/45 の対応で、Nuxt.jsからフロントエンドのURLを取得する必要があるためパラメータストアに追加する

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイント的には2かな🐱？

**Comment by kobayashi-m42** [comment]
@keitakn 
うん！2で設定するね！
