### ISSUE TITLE
Nuxtを配信するためのCloudFront + S3Bucketを作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-terraform#111]
# Doneの定義
- CloudFrontとS3Bucketで静的リソースが配信できること
- 購入した独自ドメインでアクセス出来るようになっている事

# 補足情報
LambdaとAPI Gatewayについては、https://github.com/nekochans/qiita-stocker-nuxt/issues/42 にて作成する

**Comment by kobayashi-m42** [comment]
@keitakn ストーリーポイントは、5を想定しているよ！🐱

**Comment by keitakn** [comment]
@kobayashi-m42
うん！5で問題ないと思う🐱！
