### ISSUE TITLE
静的ファイルを配信するためCloudfrontのBehaviorを追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-terraform#118]
# Doneの定義
- CloudfrontにBehaviorが追加されていること
- `/assets`にアクセスされた場合、S3から静的ファイルが配信されること

# 補足情報
 faviconなどの静的ファイルを配信することを目的としている。

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で大丈夫だと思う🐱！
