### ISSUE TITLE
Amazon AuroraのSSL/TLS 証明書のアップデート

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-terraform#128]
# Doneの定義
- 表題の件が実施されている事（Terraformの変更は必要ないかも）

>AWSでは期限を迎える2020年3月5日の1ヶ月前である 2020年2月5日 までに新CA証明書のアップデートによる影響のテストや対応を 強く推奨しています 。

# 補足情報
https://aws.amazon.com/jp/blogs/news/amazon-rds-certificate-rotation-2019/

https://techblog.timers-inc.com/entry/2019/11/07/180000

**Comment by keitakn** [comment]
# Slackでの会話メモ

ステージングは @kobayashi-m42 が対応、本番は @keitakn が対応🐱

**Comment by kobayashi-m42** [comment]
@keitakn STGは対応完了！

**Comment by keitakn** [comment]
@kobayashi-m42 本番も対応完了したよ！

両方対応完了したから、この課題はクローズで🐱
