### ISSUE TITLE
SSHキーの名前を環境毎に一意になるように修正する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-terraform#29]
# Doneの定義
- `ssh_key_pair` の名前が `stg-ssh-key`  のように環境毎に作られるようになっている事

# 補足情報
実施理由は以下の2つ。

- terraformの特性上、環境毎にリソースが作られたほうが楽だから
- リソースがスネークケースで命名されており、READMEに書かれている命名規則と合っていないから（リソース名はケバブケースでリソースIDはスネークケース）

**Comment by keitakn** [comment]
@kobayashi-m42 作業的には1行変更するだけなんだけど、依存している `bastion` とか `api` のリソースを一度再作成する必要があって、それを考慮するとストーリーポイントは2必要かなと思うんだけど、どうだろう🐱？？

**Comment by kobayashi-m42** [comment]
2でいいと思う！🐱
