### ISSUE TITLE
backendで利用するCodeBuild用のリソースを作成

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-terraform#33]
# Doneの定義
- CodeBuild用のリソースが作成されている事
- [作業中のこのPR](https://github.com/nekochans/qiita-stocker-backend/pull/147) で作成している `.env` を生成するスクリプトが正常動作しS3Bucketにアップロードされている事

# 補足情報
デプロイの流れを作る上で必要と判断した為、本件の対応は必須。
デプロイの流れは以下の通り。

1. CodeBuildが起動しプロジェクトの `.env` を生成しデプロイ用のS3Bucketにアップロードする
1. 1でアップロードされたソースコードを元にCodeDeployでデプロイを行う

これらの作業はCodePipelineで自動化する事も出来るが、この課題の中ではそこまで行わない。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイント5を想定しているよ🐱！

**Comment by kobayashi-m42** [comment]
@keitakn  うん！ポイント5で対応お願いします！🐱

**Comment by keitakn** [comment]
# めも

CodeBuild上で実行したところ以下のエラーが発生した。

```
$ DEPLOY_STAGE=stg node createDotenv.js
(node:80) UnhandledPromiseRejectionWarning: AwsEnvCreatorError: CredentialsError
 at secretsManager.getSecretValue.promise.then.catch (/codebuild/output/src513144971/src/github.com/nekochans/qiita-stocker-backend/node_modules/@nekonomokochan/aws-env-creator/dist/src/fetchSecretJson.js:19:31)
 at process._tickCallback (internal/process/next_tick.js:68:7)
(node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:80) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.29s.
```

原因はAWS-SDKのprofileが設定されていない事、しかしCodeBuild上ではロールの設定を行っておけばアクセスキーの設定は不要。（むしろ実行コンテナの中にアクセスキーを入れないようにAWS側が推奨している）

[aws-env-creator](https://github.com/nekonomokochan/aws-env-creator) をprofileを省略した場合でも正常動作するように改修する。

**Comment by keitakn** [comment]
以下のissueが解決するまでこのissueはpending.

https://github.com/nekonomokochan/aws-env-creator/issues/36
https://github.com/nekonomokochan/aws-env-creator/issues/37
