### ISSUE TITLE
qiita-stocker-frontend専用のパラメータストアを生成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-terraform#79]
# Doneの定義
SeecretManagerからFrontendに利用する環境変数が全て定義されているParameterStoreが作成されている事

# 補足
Nuxt.jsに移行した際に、Lambdaから参照することを想定。

**Comment by kobayashi-m42** [comment]
@keitakn ストーリーポイントは、3を想定🐱

**Comment by keitakn** [comment]
Kobayashi-m42 うん！3で問題ないと思う🐱
Nuxtへの移行もあるから早めに着手しても良いかもね！
