### ISSUE TITLE
FargateのCloudWatchLogsの有効期限を設定する 

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-terraform#81]
# Doneの定義
- CloudWatchLogGroupに有効期限が設定されている事

# 補足情報
今は無制限になっているのでログが溜まってくると料金が増えてしまう可能性がある。（CloudWatchLogはS3Bucket等に比べて割高）

ログの有効期限を設定し古いログが自動的に削除されるように設定するのが望ましい。

`aws_cloudwatch_log_group.retention_in_days` を設定すれば簡単に実現出来そう。

https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_group.html#retention_in_days

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは2でどうだろう🐱？

それからログの有効期限なんだけど30日くらいで十分かなと思っているけど、これもどうだろう？

**Comment by kobayashi-m42** [comment]
@keitakn 
> それからログの有効期限なんだけど30日くらいで十分かなと思っているけど、これもどうだろう？
有効期限必要だね！30日で問題ないと思う！
ストーリーポイントも2でいいと思う！🐱
