### ISSUE TITLE
バックエンドのParameterStoreから USE_IN_DOCKER を削除する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-terraform#84]
# Doneの定義
- ParameterStoreから USE_IN_DOCKERが削除されている事

# 補足情報
https://github.com/nekochans/qiita-stocker-backend/pull/186 でも触れているが既にDocker運用が前提になっているので `USE_IN_DOCKER` を削除する。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは1を想定しているよ🐱

**Comment by kobayashi-m42** [comment]
@keitakn うん！1でいいと思う！

**Comment by keitakn** [comment]
メモ
こちらは既に対応済（というか最初からUSE_IN_DOCKERはローカルでスクリプトで生成されていた）のでクローズ
