### ISSUE TITLE
qiita-stocker-frontend専用のパラメータストアを修正する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-terraform#85]
# Doneの定義
Vue.jsの設定に合わせた環境変数になっているので、パラメータストアの名前を修正する
`VUE_APP_API_URL_BASE` -> `API_URL_BASE`

**Comment by kobayashi-m42** [comment]
@keitakn 名前の変更のみだから、ストーリーポイントは1を想定しているよ！🐱

**Comment by keitakn** [comment]
@kobayashi-m42 なるほど、確かにこれは必要だね！ストーリーポイント1で大丈夫だと思う🐱
