### ISSUE TITLE
Migration用のCodeBuildプロジェクトからDEPLOY_STAGEを削除する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-terraform#89]
# Doneの定義
- 表題の件が実施されている事

# 補足情報
https://github.com/nekochans/qiita-stocker-terraform/pull/88 でCodeBuildからParameterStoreを参照するようになったのでこの変数が不要になった為。

https://github.com/nekochans/qiita-stocker-backend/issues/190 でnpm関連のタスクは実行しないように変更する予定。

**Comment by keitakn** [comment]
@kobayashi-m42 単純な削除だけだから、ストーリーポイントは1を想定しているよ🐱

**Comment by kobayashi-m42** [comment]
@keitakn 1でいいと思う！🐱
